<?php

$fix_emails = array(
    array('id' => 102184, 'old_email' => 'fr.dormeyer'), 
    array('id' => 102935, 'old_email' => 'jm.d'), 
    array('id' => 104054, 'old_email' => 'jo'), 
    array('id' => 106101, 'old_email' => 'soubeyran.fr'), 
    array('id' => 106127, 'old_email' => 'cedric.doucet0293'), 
    array('id' => 109508, 'old_email' => 'chales.az'), 
    array('id' => 109509, 'old_email' => 'chales.az'), 
    array('id' => 109847, 'old_email' => ' kholenta2@hotmail.fr'), 
    array('id' => 111174, 'old_email' => '    kairouan.trubert@gmail.com'), 
    array('id' => 112113, 'old_email' => 'fran'), 
    array('id' => 114040, 'old_email' => 'no'), 
    array('id' => 120196, 'old_email' => 'st'), 
    array('id' => 120272, 'old_email' => 'Fr'), 
    array('id' => 120572, 'old_email' => 'St'), 
    array('id' => 121533, 'old_email' => 'Cl'), 
    array('id' => 121623, 'old_email' => ' GIGM38550@hotemal.fr'), 
    array('id' => 121661, 'old_email' => 'axel-gu'), 
    array('id' => 122113, 'old_email' => 'Beno'), 
    array('id' => 122357, 'old_email' => ' fabrice.dubi@orange.fr'), 
    array('id' => 124831, 'old_email' => 'dominique.beauruel@'), 
    array('id' => 125389, 'old_email' => ' Anthonyspv@hotmail.fr'), 
    array('id' => 129973, 'old_email' => 'ghislaineetrenemasove.@sfr.fr'), 
    array('id' => 130159, 'old_email' => 'micheljfmi.@gmail.com'), 
    array('id' => 131138, 'old_email' => 'Timothé.fauci@gmail.com'), 
    array('id' => 131319, 'old_email' => 'fleuret.@orange.fr'), 
    array('id' => 131584, 'old_email' => 'jspcharbonnièremarcy@hotmail.fr'), 
    array('id' => 135896, 'old_email' => 'ericgéraldine.morin@orange.fr'), 
    array('id' => 136498, 'old_email' => 'Benoît.clabeau@gmail.com'), 
    array('id' => 143205, 'old_email' => 'hélène.garonne@orange.fr'), 
    array('id' => 145337, 'old_email' => 'bedouet.françois@gmail.com'), 
    array('id' => 147569, 'old_email' => 'loïck.grux@laposte.net'), 
    array('id' => 154475, 'old_email' => 'vergnaud.jerome.@orange.fr'), 
    array('id' => 158681, 'old_email' => 'schreiber..ddenis@neuf.fr'), 
    array('id' => 161540, 'old_email' => 'nadège.simonet0321@orange.fr'), 
    array('id' => 161607, 'old_email' => 'sarah..guyon40@gmail.com'), 
    array('id' => 162416, 'old_email' => 'marc.cadic.@orange.fr'), 
    array('id' => 165634, 'old_email' => 'florian.gaunee123.@orange.fr'), 
    array('id' => 169341, 'old_email' => 'genevieve.claudel.@gmail.com'), 
    array('id' => 182674, 'old_email' => 'stephani.@hotmail.fr'), 
    array('id' => 182811, 'old_email' => 'antho.myron.@gmail.com'), 
    array('id' => 186852, 'old_email' => 'annelise..duprat@orange.fr'), 
    array('id' => 192492, 'old_email' => 'eric..ferron50@gmail.com'), 
    array('id' => 193379, 'old_email' => 'aurélie.vertut@gmail.com'), 
    array('id' => 193577, 'old_email' => 'roger.zitter.@orange.fr'), 
    array('id' => 194155, 'old_email' => 'sergent..jerome@live.com'), 
    array('id' => 206109, 'old_email' => 'tichy.romain.@gmail.com'), 
    array('id' => 213679, 'old_email' => 'leriche..Jean-francois@orange.fr'), 
    array('id' => 215497, 'old_email' => 'jacqueline.naudey.@orange.fr'), 
    array('id' => 228915, 'old_email' => 'albi..laurent25@gmail.com'), 
    array('id' => 238112, 'old_email' => 'laverie..la.villette@free.fr'), 
    array('id' => 240739, 'old_email' => 'france..rigal@gmail.com'), 
    array('id' => 242792, 'old_email' => 'Philippesandray.@Yahoo.fr'), 
    array('id' => 252038, 'old_email' => 'melanie..hamann@hotmail.fr'), 
    array('id' => 252150, 'old_email' => 'wernett.laurence.@gmail.com'), 
    array('id' => 256516, 'old_email' => 'ellefeuvre.@yahio.com'), 
    array('id' => 259885, 'old_email' => 'alexandre..vantue@gmail.com'), 
    array('id' => 262940, 'old_email' => 'ludovic..minta@orange.fr'), 
    array('id' => 268231, 'old_email' => 'tainaalais973.@gmail.con'), 
    array('id' => 269818, 'old_email' => 'hugo.dubourdeau129.@gmail.com'), 
    array('id' => 274268, 'old_email' => 'p.bouyerpro.@gmail.com'), 
    array('id' => 81467, 'old_email' => 'fabrice.l'), 
    array('id' => 81738, 'old_email' => 'J'), 
    array('id' => 82579, 'old_email' => 's'), 
    array('id' => 84072, 'old_email' => '  peuf.maxime@orange.fr'), 
    array('id' => 84233, 'old_email' => ' cindyrella279241@msn.com'), 
    array('id' => 85282, 'old_email' => 'ang'), 
    array('id' => 85446, 'old_email' => 'matheo-jos'), 
    array('id' => 85447, 'old_email' => 'matheo-jos'), 
    array('id' => 86118, 'old_email' => 'veissiereherv'), 
    array('id' => 88216, 'old_email' => 'am'), 
    array('id' => 88360, 'old_email' => 'williard.loic'), 
    array('id' => 89883, 'old_email' => 'val'), 
    array('id' => 91277, 'old_email' => 'jean-fran'), 
    array('id' => 91278, 'old_email' => 'jean-fran'), 
    array('id' => 91462, 'old_email' => 'rhudy.desir'), 
    array('id' => 91693, 'old_email' => 'g'), 
    array('id' => 92597, 'old_email' => 'matthieu_rcs-'), 
    array('id' => 95747, 'old_email' => 'delourme-jonathan'), 
    array('id' => 97431, 'old_email' => ' danieil.vaucelle@orange.fr'), 
    array('id' => 97432, 'old_email' => ' danieil.vaucelle@orange.fr'), 
    array('id' => 97606, 'old_email' => 'pr'), 
    array('id' => 98074, 'old_email' => 'clement.roucheyrolle'), 
    array('id' => 98476, 'old_email' => ' g3.stlaurentdupont.jsp@sdis38.fr'), 
    array('id' => 98979, 'old_email' => 'lo')
); 




foreach($fix_emails as $item) {
    echo "UPDATE `ps_customer` SET email='" . $item['old_email'] . "' WHERE id_customer='" . $item['id'] . "';"; 
}